name: capstone188
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.12.1=h7934f7d_0
  - asttokens=3.0.0=py312h06a4308_0
  - blas=1.0=mkl
  - brotlicffi=1.1.0.0=py312hbdd6827_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.11.12=py312h06a4308_0
  - cffi=2.0.0=py312h4eded50_1
  - charset-normalizer=3.4.4=py312h06a4308_0
  - comm=0.2.3=py312h06a4308_0
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.4.127=0
  - cuda-runtime=12.4.1=0
  - cudatoolkit=10.1.243=h6bb024c_0
  - dav1d=1.2.1=h5eee18b_0
  - debugpy=1.8.16=py312hbdd6827_1
  - decorator=5.2.1=py312h06a4308_0
  - executing=2.2.1=py312h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.20.0=py312h06a4308_0
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py312h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - idna=3.11=py312h06a4308_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - ipykernel=6.31.0=py312h7040dfc_0
  - ipython=9.7.0=py312h06a4308_0
  - ipython_pygments_lexers=1.1.1=py312h06a4308_0
  - jedi=0.19.2=py312h06a4308_0
  - jinja2=3.1.6=py312h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - jupyter_client=8.6.3=py312h06a4308_1
  - jupyter_core=5.9.1=py312h06a4308_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libavif=1.3.0=h3539ee5_0
  - libcublas=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcusolver=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libglib=2.84.4=h77a78f3_0
  - libgomp=15.2.0=h4751f2c_7
  - libhwloc=2.12.1=default_hf1bbc79_1000
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.2.5.30=0
  - libnsl=2.0.0=h5eee18b_0
  - libnvfatbin=12.4.127=0
  - libnvjitlink=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libopenjpeg=2.5.4=hee96239_1
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.50=h2ed474d_0
  - libsodium=1.0.20=heac8642_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtasn1=4.20.0=ha30cf84_0
  - libtiff=4.7.1=h029b1ac_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.6.0=h089d785_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py312h5eee18b_0
  - matplotlib-inline=0.2.1=py312h06a4308_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py312hacdc0fc_0
  - mkl_fft=2.1.1=py312h8fe796d_0
  - mkl_random=1.3.0=py312h505adc9_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py312h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py312h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.5=py312h06a4308_0
  - numpy=2.3.5=py312h08c6c3d_0
  - numpy-base=2.3.5=py312h00548fb_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=py312h06a4308_1
  - parso=0.8.5=py312h06a4308_0
  - pcre2=10.46=hf426167_0
  - pexpect=4.9.0=py312h06a4308_1
  - pillow=12.0.0=py312h3b88751_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.5.0=py312h06a4308_0
  - prompt-toolkit=3.0.52=py312h06a4308_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py312hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py312h06a4308_0
  - pycparser=2.23=py312h06a4308_0
  - pygments=2.19.2=py312h06a4308_0
  - pysocks=1.7.1=py312h06a4308_1
  - python=3.12.12=hd17a9e1_1
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cpu
  - pyyaml=6.0.3=py312h591646f_0
  - pyzmq=27.1.0=py312hcf8288c_1
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py312h06a4308_1
  - scipy=1.16.3=py312h33bc11c_0
  - setuptools=80.9.0=py312h06a4308_0
  - six=1.17.0=py312h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.3=py312h06a4308_0
  - tbb=2022.3.0=h698db13_0
  - tbb-devel=2022.3.0=h698db13_0
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.1=py312h5eee18b_0
  - traitlets=5.14.3=py312h06a4308_0
  - typing_extensions=4.15.0=py312h06a4308_0
  - urllib3=2.5.0=py312h06a4308_0
  - wcwidth=0.2.13=py312h06a4308_0
  - wheel=0.45.1=py312h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=hb0a5e54_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - aiobotocore==2.26.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aioitertools==0.13.0
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.12.0
      - attrs==25.4.0
      - botocore==1.41.5
      - click==8.3.1
      - contourpy==1.3.3
      - cuda-bindings==12.9.4
      - cuda-pathfinder==1.2.2
      - cycler==0.12.1
      - datasets==4.4.1
      - dill==0.4.0
      - donfig==0.8.1.post1
      - einops==0.8.1
      - fonttools==4.61.0
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - google-crc32c==1.7.1
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.1.7
      - importlib-metadata==8.7.0
      - ipywidgets==8.1.8
      - jmespath==1.0.1
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - matplotlib==3.10.7
      - ml-dtypes==0.5.4
      - multidict==6.7.0
      - multiprocess==0.70.18
      - numcodecs==0.16.5
      - nvidia-cublas==13.0.0.19
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti==13.0.48
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc==13.0.48
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime==13.0.48
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cudnn-cu13==9.13.0.50
      - nvidia-cufft==12.0.0.15
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile==1.15.0.42
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand==10.4.0.35
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver==12.0.3.29
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse==12.6.2.49
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-cusparselt-cu13==0.8.0
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nccl-cu13==2.27.7
      - nvidia-nvjitlink==13.0.39
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvshmem-cu13==3.3.24
      - nvidia-nvtx==13.0.39
      - nvidia-nvtx-cu12==12.6.77
      - nvidia-physicsnemo==1.3.0
      - onnx==1.20.0
      - pandas==2.3.3
      - propcache==0.4.1
      - protobuf==6.33.1
      - pyarrow==22.0.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyparsing==3.2.5
      - pytorch-triton==3.5.1+gitbfeb0668
      - pytz==2025.2
      - s3fs==2025.10.0
      - safetensors==0.7.0
      - seaborn==0.13.2
      - shellingham==1.5.4
      - sympy==1.13.1
      - timm==1.0.22
      - torch==2.9.1+cu130
      - torchvision==0.24.1+cu130
      - tqdm==4.67.1
      - transformer-engine-cu12==2.10.0
      - treelib==1.8.0
      - triton==3.5.1
      - typer-slim==0.20.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - warp-lang==1.10.1+cu13
      - widgetsnbextension==4.0.15
      - wrapt==1.17.3
      - xarray==2025.11.0
      - xxhash==3.6.0
      - yarl==1.22.0
      - zarr==3.1.5
      - zipp==3.23.0
prefix: /home/babay/miniconda3/envs/capstone188
